### ISSUE TITLE
Django Backend?

### ISSUE THREAD

**Issue by Miserlou** [mfenniak/pg8000#102]
Has there been any work to make PG8K usable as a Django backend?

We have a great deal of use for this at the Django-Zappa project https://github.com/Miserlou/django-zappa - https://github.com/Miserlou/django-zappa/issues/3

PG8K looks like a great project, and this could be a way to extend its utility and reach.

**Comment by tlocke** [comment]
I don't know of any work on making pg8000 a Django backend, but it's a good idea.

**Comment by lospejos** [comment]
I think it'll be cool and a big plus for pg8000

**Comment by tlocke** [comment]
I think a Django backend is a good idea, but it probably needs to be done within the Django project rather than within the pg8000 project.

**Comment by ppython** [comment]
I'm not sure about third party "having to be" done in the Django project: take a look at the [django-firebird package (Firebird SQL Backend for Django)](https://github.com/maxirobaina/django-firebird).

**Comment by tlocke** [comment]
Yes, having a separate django-pg8000 project is an option too.
