### ISSUE TITLE
How does one can check if the connection is still alive and reconnect if needed ?

### ISSUE THREAD

**Issue by allan-simon** [mfenniak/pg8000#105]
I'm currently migrating a web service in python using MySQL (and pymysql) to PostgreSQL (using pg8000) and an interesting feature I was using in pymysql was the  `connection.ping(reconnect=true)` that permitted to be sure that the MySQL could go up and down without needing to restart the python service , or to do some tricks based on `SELECT 1` , does pg8000 have something similar ?

**Comment by tlocke** [comment]
Hi @allan-simon, pg8000 doesn't have such a feature. If I need to restart Postgres then I first shut down the client, restart Postgres, then start up the client.

**Comment by tlocke** [comment]
@allan-simon, thinking further about this I've come to the conclusion that it's not the responsibility of pg8000 to handle disconnects, it belongs at the level of the code using pg8000. For example, SQL Alchemy [handles disconnects in a couple of ways](http://docs.sqlalchemy.org/en/latest/core/pooling.html#dealing-with-disconnects).
