### ISSUE TITLE
Protocol description: binary vs text

### ISSUE THREAD

**Issue by robert-zaremba** [mfenniak/pg8000#107]
Hi,
Does this driver supports both protocols? Is it configurable? 
Please can you add a documentation about this?

Greetings.

**Comment by tlocke** [comment]
Have a look at:

https://github.com/mfenniak/pg8000#theory-of-operation

Does this answer your question?

**Comment by robert-zaremba** [comment]
Not really. You can encode data using the binary format or text format. Look at the following documentation section (51.1.3. Formats and Format Codes):
https://www.postgresql.org/docs/9.6/static/protocol-overview.html

**Comment by tlocke** [comment]
Pg8000 encodes the parameters in binary or text, depending on the type of the parameter. I've updated the docs at:

https://github.com/mfenniak/pg8000#theory-of-operation

to include a table of the most common types and whether they're sent as binary or text. It's not an exhaustive list, so let me know if there's a particular type that you're interested in.

**Comment by robert-zaremba** [comment]
Thanks a lot for clarification!
