### ISSUE TITLE
ArrayContentEmptyError: why are empty arrays forbidden?

### ISSUE THREAD

**Issue by fiatjaf** [mfenniak/pg8000#109]
```
ProgrammingError: (pg8000.core.ArrayContentEmptyError) array has no values [SQL: u'INSERT INTO cards (id, labels, users, syndicated) VALUES (%s, %s, %s, %s)'] [parameters: (u'5712370b81f081', [], [], [])]
```

The code for `array_inspect` checks for the first element of each array passed as argument to decide its oid. It [fails](https://github.com/mfenniak/pg8000/blob/58ce60fc4433d8283ed100a0c90ae6b2e7b689d4/pg8000/core.py#L2163-L2165) if the array is empty, but if the element [type is unknown it defaults to string](https://github.com/mfenniak/pg8000/blob/58ce60fc4433d8283ed100a0c90ae6b2e7b689d4/pg8000/core.py#L2202-L2204).

So why can't it assume it is a string when the array is empty?

**Comment by tlocke** [comment]
Good point. I've done as you suggest at https://github.com/mfenniak/pg8000/commit/2b51e7dcc66f801db6c829cc434fe44f1f33f3e7
