### ISSUE TITLE
Does pg8000 suport dict cursor?

### ISSUE THREAD

**Issue by ygl-rg** [mfenniak/pg8000#112]
Hi All

```
dict cursor is supported in psycopg2 and it is a nice feature. I want to know whether pg8000 supports it.

I have checked the doc but found nothing about it.
```

**Comment by mfenniak** [comment]
Hey ygl-rg.  pg8000 does not currently support retrieving rows from the database in a dict.

**Comment by kajuberdut** [comment]
If this will help anybody looking at this issue, here is a very simple version to get rows as a dictionary:
```
def dictfetchall(sqltext):
    """ Returns query results as list of dictionaries."""
    conn = connect()
    cursor = conn.cursor()
    result = []
    cursor.execute(sqltext)
    cols = [a[0].decode("utf-8") for a in cursor.description]
    for row in cursor.fetchall():
        result.append({a:b for a,b in zip(cols, row)})
    return result

```

**Comment by Stvad** [comment]
Hey @tlocke I've noticed that you closed this issue, but I can't find anything referencing this in the recent release notes. I was wondering what is the status of this one? Thanks!

**Comment by tlocke** [comment]
Hmm, I'm not sure about this. It's outside the DB-API specification, so I'm reluctant.
