### ISSUE TITLE
"WARNING: not in a transaction" difference from psycopg2 and workaround

### ISSUE THREAD

**Issue by jamadden** [mfenniak/pg8000#113]
I'm one of the maintainers of [RelStorage](http://relstorage.readthedocs.io), a relational-database backend for [ZODB](http://zodb.readthedocs.io).

RelStorage has supported running on PostgreSQL for a long time (in fact it was originally *only* PG), always using the `psycopg2` driver (and lately the `psycopg2cffi` driver). I've [been working](https://github.com/zodb/relstorage/pull/98) to add support for pg8000 (it has many advantages like being gevent compatible, which I also maintain).

First, thanks for the awesome library. It was a snap to take the psycopg2 code and get it working with pg8000. Amazing work! RelStorage's extensive test suite runs without a flaw.

Well, there is one tiny flaw. When using pg8000, the PostgreSQL server generates *hundreds* of messages: "WARNING: not in a transaction". 

I turned on statement logging, and discovered that these were always due to a COMMIT immediately followed by a ROLLBACK. This is a sequence that RelStorage has in some cases, and the nature of RelStorage makes that a difficult scenario to avoid.

psycopg2 handles this natively in the client by simply not sending the rollback if the connection state isn't in a transaction. Here's the code for its python version, psycopg2cffi:
```python
    def _rollback(self):
        with self._lock:
            if self._autocommit or self.status != consts.STATUS_BEGIN:
                return
            self._mark += 1
            try:
                self._execute_command('ROLLBACK')
            finally:
                self.status = consts.STATUS_READY
```

In looking at pg8000, I noticed the Connection keeps track of a `in_transaction` variable. I modified RelStorage [to subclass Connection](https://github.com/zodb/relstorage/blob/d94b8415e4472d55811a91bc6298651c6d39a854/relstorage/adapters/_postgresql_drivers.py#L177) and use that variable to do the same thing, and the warnings stopped, while the tests continue to pass. I was happy.
```python
    class _DoesNotRollbackIfNotInTransaction(pg8000.Connection):

        def rollback(self):
            if not self.in_transaction:
                return
            return super(_DoesNotRollbackIfNotInTransaction,self).rollback()
```

So I was wondering if this is a good idea, or if there's some reason that it wouldn't be? If it is a good idea, is this an enhancement you'd be willing to add to pg8000 itself? I can do a PR if that would be helpful.

**Comment by mfenniak** [comment]
Hi Jason, thanks for putting together such a clear issue report. I think the behaviour you're describing sounds great, I can't forsee any reason that change would be an issue.

If you threw together a PR, I'd gladly merge it if there are no test failures and if @tlocke doesn't pipe in with any contrary thoughts.

**Comment by jamadden** [comment]
Opened pr #3.  Fingers crossed for CI.
