### ISSUE TITLE
Ability to execute .sql file

### ISSUE THREAD

**Issue by JanBerktold** [mfenniak/pg8000#117]
Right now the ability to execute a sql-file with multiple statements in it is missing.

It is also not possible to _read_ the file into an _execute_ statement as it uses a prepared statement and therefore only allows a single command per function call.

**Comment by tlocke** [comment]
Yes, with pg8000 you can only execute one query at a time.

**Comment by djsd123** [comment]
For anyone coming across this issue;

I needed a pure python Postgres driver to use within an AWS Lambda function to run arbitrary SQL inc SQL files.  As stated above this is not possible with pg8000 as it uses a prepared statement. 

Workaround:
[sqlparse](https://sqlparse.readthedocs.io/en/latest/)

```
import pg8000
import sqlparse

def lambda_handler():

    connection = pg8000.connect(
        user='postgres',
        password='mysecretpassword',
        host='localhost',
        database='postgres'
    )

    cursor = connection.cursor()

    file = open('script.sql', 'r')

    statements = sqlparse.split(file.read())

    for statement in statements:
        cursor.execute(statement)

    connection.commit()
    cursor.close()
    file.close()

```  

Cleaner in my opinion that say, reading the file and splitting on `;`

**Comment by maddy2u** [comment]
This would be nice to have it implemented in pg8000 directly.
