### ISSUE TITLE
Prepared statements are never deallocated

### ISSUE THREAD

**Issue by nextghost** [mfenniak/pg8000#118]
I've discovered two closely related memory management issues in Connection._caches. Python script using the pg8000 module and/or the PostgreSQL server may run out of memory when the connection is active for extended period of time and either of the following conditions is met:
1. The script executes large numbers of unique queries (e.g. by expanding arguments into the query string itself rather than passing them through placeholders).
2. The script frequently executes CREATE or ALTER queries.

The first problem is that Connection._caches has no limit on number of cached query strings/prepared statements. Every single unique query string will be stored until the connection is closed (with one exception that leads to the second problem). I know that expanding arguments into query string is bad practice but unfortunately PyDAL does exactly that. Which means that Web2Py scheduler can eat upwards of 2GB RAM per day through this leak just by checking the database for new tasks. (Yes, I intend to fix that as well.)

You should add a configurable limit for the number of queries stored in Connection._caches and clean up when the cache gets full.

The second problem is that client-side prepared statements are dropped from Connection._caches every time a CREATE or ALTER query is executed, but the prepared statements in question are never deallocated on the server side. So even a well-behaved program that uses placeholders properly will reallocate the same prepared statements over and over until the PostgreSQL server itself runs out of memory, every time a DDL query is executed. (Note that this doesn't provide a viable workaround for the other problem because converted query strings are never dropped from cache.)

The cache is cleared at the end of Connection.handle_COMMAND_COMPLETE(). This is trivial to fix, simply send DEALLOCATE ALL command to the server.

Here's a demonstration script for the first problem (WARNING: 100,000 iterations will consume about 3GB of RAM):

```
conn = pg8000.connect(...)
cursor = conn.cursor()
cursor.execute('CREATE TEMPORARY TABLE leaktest (value INTEGER)')
cursor.execute('INSERT INTO leaktest (value) VALUES (0)')
conn.commit()
query = 'UPDATE leaktest SET value={0}'

for val in range(100000):
    cursor.execute(query.format(val))
    conn.commit()
cursor.execute('SELECT count(*) FROM pg_prepared_statements')
print 'Number of prepared statements allocated:', cursor.fetchall()[0][0]
```

Here's a demonstration script for the second problem:

```
conn = pg8000.connect(...)
cursor = conn.cursor()
cursor.execute('CREATE TEMPORARY TABLE leaktest (value INTEGER)')
cursor.execute('INSERT INTO leaktest (value) VALUES (0)')
conn.commit()
query = 'UPDATE leaktest SET value=%s'

for cycle in range(10000):
    cursor.execute('ALTER TABLE leaktest ALTER COLUMN value SET NOT NULL')
    conn.commit()

    for val in range(10):
        cursor.execute(query, [val])
        conn.commit()
cursor.execute('SELECT count(*) FROM pg_prepared_statements')
print 'Number of prepared statements allocated:', cursor.fetchall()[0][0]
```

The ALTER and UPDATE queries, BEGIN TRANSACTION and COMMIT will be reallocated from scratch on the server in every iteration of the outer `for` cycle. If you comment out just the ALTER query, the total number of prepared statement will drop from 40006 to 7. PostgreSQL server will allocate about 200MB of RAM for the duplicate prepared statements. Feel free to increase the number of ALTER cycles to see the full extent of the resource leak.

**Comment by mfenniak** [comment]
Hey @nextghost, thanks for reporting this.  This is clearly a pretty huge oversight in the caching.  Even if you weren't materializing your queries before they reached pg8000, this is still a huge problem for any long-running app that might do dynamic queries, or use per-tenant database schemas, or... well, lots of other scenarios I'm sure.

**Comment by tlocke** [comment]
Hi @nextghost, I've made a change so that if pg8000 forgets a prepared statement because there's been some DDL executed (ALTER, CREATE etc), it now also closes it on the server https://github.com/mfenniak/pg8000/commit/c0fdd64b73de3623d1cbf4fa9eb205156f7ee53c. That still leaves the problem of a large number of unique queries causing lots of prepared statements though.

**Comment by tlocke** [comment]
With https://github.com/mfenniak/pg8000/commit/bdadf48379eb28b4de8cf716e593205054480b3e, there's now an upper limit `pg8000.max_prepared_statements` to the number of prepared statements that pg8000 keeps track of. When that number is exceeded, they're all closed.
