### ISSUE TITLE
Error while accessing external database table with integer 

### ISSUE THREAD

**Issue by nikhilsmenon** [mfenniak/pg8000#119]
Version - pg8000-1.10.1
                   py2.6

I have below script which try to access an external database table with integer type init. this works if I alter table to have varchar instead of integer. it was working if database is same system.

import pg8000

conn = pg8000.connect(user="mpspostgres",
host="10.102.31.123", port=11921, database="mydb")
cursor = conn.cursor()

def readTable():
    result = (cursor.execute("SELECT \* FROM tm"))
    results = cursor.fetchall()
    for row in results:
        print row
schema of tm
Table "public.tm"
            Column            |          Type          | Modifiers
------------------------------+------------------------+-----------
id                           | character varying(14)  | not null
name                         | character varying(100) |
tenant_group_id              | character varying(14)  |
isdefault                    | character varying(14)  |
max_devices_to_autoprovision | integer                |
Indexes:
    "tm_pkey" PRIMARY KEY, btree (id)

Error is 
  File "test_pg8000.py", line 14, in <module>
    readTable()
  File "test_pg8000.py", line 8, in readTable
    result = (cursor.execute("SELECT \* FROM tm"))
  File "/var/mps/python/lib/python2.6/site-packages/pg8000-1.10.1-py2.6.egg/pg8000/core.py", line 568, in execute
  File "/var/mps/python/lib/python2.6/site-packages/pg8000-1.10.1-py2.6.egg/pg8000/core.py", line 1684, in execute
  File "/var/mps/python/lib/python2.6/site-packages/pg8000-1.10.1-py2.6.egg/pg8000/core.py", line 1755, in handle_messages
  File "/var/mps/python/lib/python2.6/site-packages/pg8000-1.10.1-py2.6.egg/pg8000/core.py", line 1745, in handle_DATA_ROW
  File "/var/mps/python/lib/python2.6/site-packages/pg8000-1.10.1-py2.6.egg/pg8000/core.py", line 393, in int4_recv
struct.error: unpack_from requires a buffer of at least 4 bytes

Best Regards,
Nikhil

**Comment by mfenniak** [comment]
Huh, that's really weird.  Can you describe the platforms of the client and the database server?  eg. LInux on x86-64, OSX, something else?

**Comment by nikhilsmenon** [comment]
FreeBSD

**Comment by nikhilsmenon** [comment]
Anybody faced the issue? pg8000 library with external db throws error for
integer. tried bigint and tinyint but fixed types has unpacking error.

Best Regards,
Nikhil

**Comment by mfenniak** [comment]
Hi Nikhil.  I've never seen this issue before; I still suspect it is an issue that is specific to your platform, either on the server-side or the client-side.  I was hoping you could provide more information than just "FreeBSD"; eg. the system architecture (i386, amd64, arm, arm64,...) of both your client (where you're executing the Python script) and your PostgreSQL server.

It would also be very helpful if you could try to reproduce this with your code & database schema on a more typical platform like Linux x64.  That could either confirm my suspicions, or, invalidate them.

**Comment by nikhilsmenon** [comment]
I tried the same pg8000 script from windows box (64 bit ). its giving same
error. But my pgxl (postgres -XL) server as i said is running 64 bit
FreeBSD. One point to be noted is that if my database is internal its
working. If client is outside then I am seeing this issue.

**Comment by nikhilsmenon** [comment]
The pg8000 library's core.py has handle_DATA_RAW function which on type
integer uses int4_recv function. This function fails is byte order is
changed due to external database. (because of network byte order the
function gives wrong values). Also if the integer is less than 4 digits
(upto 999) its gives struct.un_pack error.

Do we need to do anything special if external db is used or (handle byte
ordering) ?
Best Regards,
Nikhil

**Comment by nikhilsmenon** [comment]
System details: All system are..

bash-2.05b# uname -m
*amd64*
bash-2.05b# python
Python *2.6.6* (r266:84292, Jun  3 2016, 12:15:31)
[GCC 4.2.1 20070831 patched [*FreeBSD*]] on freebsd8
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.byteorder
*'little'*

**Comment by radi9** [comment]
I got this issue also, and my env is 
freebsd 9 with pgsql server 9 and pg800 driver 1.9.14,
it's weird that this only happened on a table and the other tables just works fine.

**Comment by tlocke** [comment]
I'm afraid I'm stumped by this, but if you work out what's going on I'm happy to make a modification to pg8000.

**Comment by tlocke** [comment]
I'll close this issue for now, but please do re-open if you have any solution.

**Comment by IanMeyers** [comment]
I've got this issue appearing in a project that uses pg8000: https://github.com/awslabs/amazon-redshift-utils/issues/239. The issue appears to have been introduced in 1.10.6, but I've looked through the revision history and don't see anything obvious in core.py that causes the problem. In our case, the issue only happens when running in a Docker container, but not when run from outside. Very strange!

**Comment by AlecBenzer** [comment]
Also running into this with an AWS Lambda talking to Postgres 9.6.3 on AWS RDS.

**Comment by AubreyF** [comment]
I'm running into the same issue communicating with a Google App Engine "managed SQL" PostgreSQL 9.6 instance from both windows and linux clients running Python 2.7. Unfortunately, inside Google's Standard App Engine environment, pg8000 is our only simple option for communicating directly with PostgreSQL DBs.
