### ISSUE TITLE
Please sign release tarballs

### ISSUE THREAD

**Issue by Natureshadow** [mfenniak/pg8000#122]
Hi!

I am a maintainer of the Debian python-pg8000 package. It would be helpful if you could pgp-sign your next source tarballs on PyPI.

Cheers,
Nik

**Comment by tlocke** [comment]
Hi @Natureshadow I've amended the release steps in the README so that the next release will be signed:

https://github.com/mfenniak/pg8000/commit/46a7e8fffd55ba7e40ddf87ff02c70e9ed3b239d

**Comment by Natureshadow** [comment]
Hi,

>Hi @Natureshadow I've amended the release steps in the README so that
>the next release will be signed:

Great, thank you!
