### ISSUE TITLE
sqlalchemy func.count(‘*’) failed

### ISSUE THREAD

**Issue by jfilix79** [mfenniak/pg8000#123]
when work with sqlalchemy, the query:
 db.session.query(func.count('*)).select_from(self.model)
failed, produce:
ProgrammingError: (pg8000.core.ProgrammingError) (u'ERROR', u'ERROR', u'42P18', u'could not determine data type of parameter $1', u'postgres.c', u'1344', u'exec_parse_message', u'', u'') [SQL: u'SELECT count(%s) AS count_1 \nFROM projects'] [parameters: ('*',)]
and,
 db.session.query(func.count(self.model.id)).select_from(self.model)   works fine.

**Comment by jfilix79** [comment]
db.session.query(func.count())  works fine.

**Comment by tlocke** [comment]
Hi @jfilix79, to work out where the problem is I think you need to get SQLAlchemy to show you the SQL it is producing. Then you can reproduce the problem without SQLAlchemy and we'd be in a better position to help.
