### ISSUE TITLE
"could not determine data type of parameter $1" executing a manual prepared statement

### ISSUE THREAD

**Issue by jamadden** [mfenniak/pg8000#132]
I have a large code base (RelStorage) that supports psycopg2, psycopg2cffi, and pg8000.

I'm trying to add the use of some parameterized prepared statements. Under psycopg2 for our hottest queries this can result in a 30-40% performance improvement.  Something like this:

```python
cursor.execute('PREPARE load_current (BIGINT) AS SELECT thing FROM table WHERE col = $1')

# later
cursor.execute('EXECUTE load_current(%s)', (1,))
```

Under pg8000 1.10.6, however, this raises the following error:
```
  File "//lib/python3.4/site-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "//lib/python3.4/site-packages/pg8000/core.py", line 1940, in execute
    self.handle_messages(cursor)
  File "//lib/python3.4/site-packages/pg8000/core.py", line 2088, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', 'ERROR', '42P18', 'could not determine data type of parameter $1', 'postgres.c', '1344', 'exec_parse_message', '', '')
```

Am I doing something wrong? Is there a way to make this work?

I appreciate any help, thanks!

**Comment by tlocke** [comment]
Actually pg8000 always uses prepared statements, using the underlying PostgreSQL protocol. However, using them in SQL will still work. To solve the problem you're having, do an explicit cast of the parameter (in the SQL statement). I'm a bit rushed, so forgive the brief answer!

**Comment by jamadden** [comment]
Thanks for the suggestion!

I tried adding `::BIGINT` (or `CAST`) everywhere I could think of, most notably including the statement that was being complained about (`cursor.execute('EXECUTE load_current(%s::BIGINT)', (0,))`), but that didn't make any difference. The server logs:
```
STATEMENT:  EXECUTE load_current($1::bigint)
ERROR:  could not determine data type of parameter $1
```

So I started looking at the bytes that are being sent on the wire. I traced through the code and saw that each incoming argument is converted to a postgresql type OID, and that type number is sent as part of the PARSE message. In an effort to effect the bytes on the wire, I pre-encoded my integer 0 as a str, but the code for `str` and `int` are both 705, e.g., unknown, resulting in this error. (For reference, here's the byte array of the message: `bytearray(b'pg8000_statement_8\x00EXECUTE load_current($1::bigint)\x00\x00\x01\x00\x00\x02\xc1')`)

So just to change it up, I encoded the `str` as `bytes`, because that *does* have a distinct type code, 17. That results in these bytes: `bytearray(b'pg8000_statement_8\x00EXECUTE load_current($1::bigint)\x00\x00\x01\x00\x00\x00\x11')` (i.e, one parameter of type 17).

It also results in the server producing error 42P02:
```
ERROR:  there is no parameter $1 at character 22
STATEMENT:  EXECUTE load_current($1::bigint)
```

Intrigued, I tried something similar in the shell:
```
relstoragetest_hf=> prepare stmt (bigint) as select tid from object_state where zoid = $1;
PREPARE
relstoragetest_hf=> prepare stmt2 as execute stmt($1);
ERROR:  syntax error at or near "execute"
LINE 1: prepare stmt2 as execute stmt($1);
                         ^
```

That suggests to me that it may not be possible/supported to prepare an EXECUTE statement. Could that be the case?

**Comment by donalm** [comment]
When you were testing different casts, did you try this:

`cursor.execute('PREPARE load_current AS SELECT thing FROM table WHERE col = $1::BIGINT')`

**Comment by jamadden** [comment]
I did yes. I double checked just now. It produces the same error.

**Comment by tlocke** [comment]
I've had a look at this and it seems that pg8000 will always fail with an EXECUTE that has parameters. Unlike with other queries, a cast won't work if PostgreSQL can't determine the parameter type. Does this matter? Well since pg8000 always uses implicit prepared statements, nothing is gained by using explicit ones. I've explained this at:

https://github.com/tlocke/pg8000/blob/master/README.adoc

which I'll push to the main repo if everyone's okay with that.

**Comment by jamadden** [comment]
I'd guessed my way to much the same conclusion :)

The only reason that I can see that it matters is for codebases that want to support other DB-API compliant drivers (such as psycopg2/cffi) in the most efficient way possible, which means using manually prepared statements for them, and not on pg8000. So far, that's been basically the only change RelStorage (a large, multi-db, multi-driver package) has had to make for pg8000 support. And admittedly, it [really wasn't that much code](https://github.com/zodb/relstorage/commit/12b46e13c40c47582fbaefb41d1e54bc4c3cca95#diff-b4a2cae0f565df6b7c020b2b7a5f22f3R233)---part of that could be that the codebase was already designed to handle things like this, and part of that could be that I'm limited in the ways that I can use prepared statements due to other limitations I've run into in the multi-db, multi-driver model.

If it's possible to detect this case at PARSE time, a more explicit error message might be a nice addition.

**Comment by tlocke** [comment]
We've made a change to pg8000 to make it send integers as the closest Postgres integer type: https://github.com/mfenniak/pg8000/commit/14e03bab8b812a73f7e1ef4686d0366543e18ebf so that should solve the particular problem you were having.
