### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by the1337guy** [mfenniak/pg8000#137]
There are many open issues with no comments and 5 PRs to be merged?

I guess this project has been abandoned as the last commit was in Jan.

**Comment by mfenniak** [comment]
Unfortunately I don't currently have the time or interest to invest into this project.  @tlocke participating as a contributor and putting a big amount of his time into it for a while, but he might have lost interest or availability as well.

I'd welcome adding a new contributor if someone is interested in helping out.

**Comment by tlocke** [comment]
pg8000 isn't abandoned, just going through a lull. @the1337guy and @pmukherjeee you may have prompted me to take some action :-)

**Comment by tlocke** [comment]
I've made a few changes and done a new release, so I think we can close this issue.
