### ISSUE TITLE
cannot set SSL trust roots

### ISSUE THREAD

**Issue by glyph** [mfenniak/pg8000#148]
RDS uses a custom trust root for SSL on RDS databases.  Therefore, in order to securely use an RDS database with PG8000, it is necessary to set `ssl=True` and to also pass a custom value to `ssl.wrap_socket`'s `ca_certs` parameter.  `pg8000` does not currently allow this, or provide any public API hook to insert one's own transport mechanism.

**Comment by glyph** [comment]
I've filed a related issue against sqlalchemy: https://bitbucket.org/zzzeek/sqlalchemy/issues/4146/common-handling-of-sslmode-and-sslrootcert but it might be nice if pg8000 itself had a URL-based connection mechanism as well, that mirrored libpq's.

**Comment by tlocke** [comment]
Thanks for the PR, I've added this now.
