### ISSUE TITLE
Dynamic JSON from a fetchall and it possible a column assign?

### ISSUE THREAD

**Issue by DrakoRod** [mfenniak/pg8000#153]
Hi folks! 

I'm developing a library with pg8000 but a don't understand how to generate a dynamic JSON from a fetchall() query. When I try generate directly show this error: 

`ERROR: datetime.datetime(2018, 3, 6, 19, 22, 12, 124851, tzinfo=<pg8000.core.UTC object at 0x7f267d3afd90>) is not JSON serializable`

I was looking for a example but I don't found. I want generate json something like that: 

`{ "name":"John", "age":31, "city":"New York" }`

Best Regards!

**Comment by bjmc-globus** [comment]
This is not a `pg8000` bug, it's just a limitation of the standard Python `json` module that it can't serialize datetimes. There's [plenty of workarounds out there](https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable) but they're not really anything to do with this library.

**Comment by tlocke** [comment]
I agree with @bjmc-globus. One solution is to use [Zish](https://github.com/tlocke/zish).
