### ISSUE TITLE
Connecting to a database via UNIX trust

### ISSUE THREAD

**Issue by dorfsmay** [mfenniak/pg8000#155]
Is it possible to connect to a database via "UNIX trust" like psql and psycodb2 do by default?

**Comment by tlocke** [comment]
Do you mean a UNIX socket? That's possible with pg8000, see the `unix_sock` parameter of the [`connect` method](https://github.com/tlocke/pg8000#pg8000connectuser-hostlocalhost-unix_socknone-port5432-databasenone-passwordnone-sslnone-timeoutnone-application_namenone-tcp_keepalive).
