### ISSUE TITLE
Losing lowercase `u` with string interpolation?

### ISSUE THREAD

**Issue by iamchairs** [mfenniak/pg8000#158]
I've found a strange issue where it appears lowercase `u` characters are getting removed with `%s` string interpolation is used.

```
cursor.execute("""
            INSERT INTO public.foo
            (names)
            VALUES
            (%s)
        """, (['HustonU']))
```

Would insert

```
{HstonU}
```

Has anyone encountered this before?

**Comment by tlocke** [comment]
Hi @iamchairs I think Python needs a comma for a tuple with one item, so perhaps the code should look like:

```
cursor.execute("""
            INSERT INTO public.foo
            (names)
            VALUES
            (%s)
        """, (['HustonU'],))
```
