### ISSUE TITLE
Big number of parameters in query causes connection.execute to fail

### ISSUE THREAD

**Issue by MrP4p3r** [mfenniak/pg8000#162]
This line of code in method execute of Connection does not allow to have more than 32767 query parameters:
```val.extend(h_pack(len(params)))```

Is there a workaround?

**Comment by tlocke** [comment]
Hmm, good question! Looking at the [message formats](https://www.postgresql.org/docs/current/protocol-message-formats.html) and specifically at the `Bind` format, it says for this parameter:

> Int16
> 
>     The number of parameter values that follow (possibly zero). This must match the number of parameters needed by the query.

So the limit is a 16 bit integer. Now is that signed or unsigned? `Int16` can be negative in certain situations, so perhaps it always has to be signed? I don't know enough about the protocol to know if it's safe to change it to unsigned for this case, but if you can find out that's it's okay then I'm happy to change it.

**Comment by MrP4p3r** [comment]
PostgreSQL does not seem to have unsigned integer types even in protocol messages. Even if this works it should be considered more like a hack than legit solution.

AFAIU bind message does not execute query but prepares query for execution. Maybe it is possible to send query and parameters in multiple bind messages?

**Comment by tlocke** [comment]
Hmm, I don't think multiple bind messages would work, from reading https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

> If successfully created, a named portal object lasts till the end of the current transaction, unless explicitly destroyed. An unnamed portal is destroyed at the end of the transaction, or as soon as the next Bind statement specifying the unnamed portal as destination is issued. (Note that a simple Query message also destroys the unnamed portal.) Named portals must be explicitly closed before they can be redefined by another Bind message, but this is not required for the unnamed portal. Named portals can also be created and accessed at the SQL command level, using DECLARE CURSOR and FETCH.

So whether you use unnamed or named portals, you can't have a BIND with the same portal.
