### ISSUE TITLE
Encountered struct.error when handling terminated connection

### ISSUE THREAD

**Issue by gtmsingh** [mfenniak/pg8000#165]
**Context:** 
I was trying to handle a session which can be terminated by another session.

**Issue:** 
Apart from issue like - Unix gives _BrokenPipeError_ and NT based system gives _ConnectionResetError_, I encountered weird issue with connection resets:
![image](https://user-images.githubusercontent.com/8234335/44516467-cdc72400-a6e2-11e8-8600-7139d8e4694c.png)

**Workaround:**
 I have handled _struct.error_ too

**Doubts:**
1. Why it happens that sometimes I get _BrokenPipe_ and sometimes _struct.error_ exception?
2. Is there a way I can force one of them to occur OR handling both of them is actually a best practice?

**Platform details:**
1. DB: Postgres 9.6.10
2. Environment: gitlab runner v11.0.0

**Comment by tlocke** [comment]
Hi @gtmsingh, I've had a think about this, and my theory is that you get a `BrokenPipeError` when pg8000 is _writing_, but  you get the `struct.error` when pg8000 is _reading_.  Does that fit with what you're seeing?

**Comment by tlocke** [comment]
When I talk about reading I mean low-level reading, ie. data being read from the socket.

**Comment by gtmsingh** [comment]
I don't think I went into that detail. Assuming that your theory is correct (which clarifies my 1st doubt), I would like to understand that having 2 different errors (specially from very different module) is a good practice or is it better that these error should be wrapped in one/similar exception?
