### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by LispEngineer** [mfenniak/pg8000#169]
Just a quick thank you for this driver. I had to connect to a PostgreSQL RDS instance in an AWS Lambda Python 3.6 function, and your driver worked out of the box, unlike the psycopg2 driver on which I wasted half a day of my life.

Thank you also for having just one and not 5,914 dependencies for me to deal with.

**Comment by tlocke** [comment]
Great, glad you had a good experience with pg8000 :-) We don't get many thank yous, so much appreciated.
