### ISSUE TITLE
Connection should support __enter__ and __exit__

### ISSUE THREAD

**Issue by seushermsft** [mfenniak/pg8000#170]
Cursor already supports this and allows for using the `with` keyword, but Connection doesn't so you have to fall back to using try-finally with checks to see if the connection object was properly initialized.

**Comment by seushermsft** [comment]
@tlocke (you seem to be most active) - Is there a process to follow for commits in the repro, and any tips to get the current set of tests succeeding? My local run of master fails with the same errors CircleCI is and I don't know if that is a known issue, or a coincidence. - Thanks

**Comment by tlocke** [comment]
Hi @seushermsft, I've used this patch and it'll be in the next release. We went through a bit of confusion with moving from CircleCI to Travis, and moving the repository to https://github.com/tlocke/pg8000/, but everything should be working now.
