### ISSUE TITLE
'ERROR', 'XX000', 'no unpinned buffers available'

### ISSUE THREAD

**Issue by robochat** [mfenniak/pg8000#37]
I've recently upgraded to pg8000 1.9.9 from 1.08. I have a system that writes continuously to a database and it now only works for about 12 hours before I get the error
pg8000.errors.ProgrammingError: ('ERROR', 'XX000', 'no unpinned buffers available')
Currently I execute quite a few statements per transaction, could that be the problem?
Could someone tell me what this means?

**Comment by tlocke** [comment]
I haven't been able to reproduce this bug, and haven't had any more reports. We did simplify the main event handling loop, so I'll close this issue in the hope that that's fixed it. Please do re-open if it happens again.
