### ISSUE TITLE
load credentials from .pgpass file

### ISSUE THREAD

**Issue by ssbarnea** [mfenniak/pg8000#47]
libpq implementations do load credentials from the .pgpass file.

pg8000 should load credentials from inside the ~/.pgpass file, as the other drivers.

This is very important because putting credentials in source code is a very bad practice and now the alternative is to manually implement the read of these from somewhere else, instead of loading them from the standardised location.

**Comment by lsh-0** [comment]
no `.pgpass` support? **really**?? urgh. can we at least get a mention in the readme or in the docs when setting up a connection that it's not supported?
