### ISSUE TITLE
add support for ssh tunnel connection

### ISSUE THREAD

**Issue by ssbarnea** [mfenniak/pg8000#61]
some database connection clients do support connecting via SSH tuneling. One such example is Navicat, which can connect using a SSH tunnel. This is extremely useful because postgresql post 5432 is usually blocked by most firewalls, but SSH port (22) is not, allowing use to connect to remote servers.

**Comment by hilios** [comment]
The add of this feature will have to introduce a new kind of connection string, where a simple ssh command should be enough for connecting at `127.0.0.1:5432` for instance:

Here it's a boilerplate to create the SSH tunnel:

```bash
$ ssh -NT -L 5432:localhost:5432 youruser@yourserver.com
```
