### ISSUE TITLE
OperationalError exception

### ISSUE THREAD

**Issue by ilvalle** [mfenniak/pg8000#73]
pg8000 doesn't raise an OperationalError Exception (as stated by the DB-API 2.0 specification) when it tries to use a 'broken connections'. Instead an *[Errno 32] Broken pipe* exception is raised.
A broken connection is for example when the db is restarted while the application is sleeping.
In web2py I'd support such kind of situations but it is complex to deal with drivers raising their own exceptions. See discussion https://groups.google.com/d/topic/web2py-developers/e161iZZmp0Y/discussion

**Comment by tlocke** [comment]
Yes, I think you're right. I'll code something up.

**Comment by tlocke** [comment]
I've put a fix at https://github.com/tlocke/pg8000/commit/97b712a6e4ab00ee48ce9872caae2eead77cea99. If everyone's happy with it I'll push it to the main repo.

**Comment by mfenniak** [comment]
Seems a reasonable fix to me.

**Comment by tlocke** [comment]
Cool, I've pushed this to the main repo. Perhaps it's time for a new release?
