### ISSUE TITLE
Handle EmptyQueryResponse

### ISSUE THREAD

**Issue by wsanchez** [mfenniak/pg8000#74]
I have been getting an exception with a traceback that ends with:

	  File "/Volumes/data/Users/wsanchez/Developer/CalendarServer/pg8000-1/.develop/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 1756, in handle_messages
	    self.message_types[code](self._read(data_len - 4), cursor)
	exceptions.KeyError: 'I'

Which seems to imply that pg8000 isn't handling a message type of some sort.  After a bit of digging, I found the Postgres docs on [Message Formats](http://www.postgresql.org/docs/current/static/protocol-message-formats.html), which I think indicates the message type in question is `EmptyQueryResponse`, if I'm reading this correctly.

**Comment by tlocke** [comment]
Hi @wsanchez, thanks for the bug report. The EmptyQueryResponse seems to indicate that the server received an empty query string. I've made a commit at my repo at https://github.com/tlocke/pg8000/commit/201e61370e2dcf3ba342b8eeb7c9304de15a57a6 that handles this message by raising a ProgrammingError.

**Comment by tlocke** [comment]
I've pushed this to the main repo now. Please re-open if there's still a problem.
