### ISSUE TITLE
flake8 fails on recent checkins

### ISSUE THREAD

**Issue by mfenniak** [mfenniak/pg8000#75]
Hey @tlocke, looks like your recent commits to master broke the flake8 run in tje continuous integration: https://circleci.com/gh/mfenniak/pg8000/74

**Comment by tlocke** [comment]
Oops, sorry! I was using an old version of flake8 on my machine. Anyway, fixed now https://circleci.com/gh/mfenniak/pg8000/75.

**Comment by mfenniak** [comment]
Great. :-)
