### ISSUE TITLE
issue with release 1.10.2

### ISSUE THREAD

**Issue by ilvalle** [mfenniak/pg8000#76]
Release 1.10.2 fails https://github.com/web2py/pydal tests,after an error, the build doesn't terminate. 
All other tested drivers passed successfully.
Have a look at https://travis-ci.org/ilvalle/pydal/builds/54942272

**Comment by ilvalle** [comment]
I fixed it on pydal https://github.com/web2py/pydal/pull/90/files
The mentioned build hanged without terminating, I'm not sure why

**Comment by tlocke** [comment]
Do we think this is still a problem with pg8000?
