### ISSUE TITLE
Cursor.lastrowid

### ISSUE THREAD

**Issue by ilvalle** [mfenniak/pg8000#79]
DB-API https://www.python.org/dev/peps/pep-0249/#lastrowid
in pg8000 Cursor doesn't have such attribute.

**Comment by tlocke** [comment]
I believe that lastrowid is an optional extension, and you're right, pg8000 doesn't implement it. If it would be useful to you, we could set lastrowid to the oid of the last inserted row (if it has one). Would that be of use?

**Comment by abspoel** [comment]
Note (in case someone's search for this leads them here, as mine did): to get the last inserted ID you can also use PostgreSQL's `RETURNING` clause, e.g.

    cur.execute("INSERT INTO table (a) VALUES ('1') RETURNING id")
    id_ = cur.fetchone()[0]

**Comment by mfenniak** [comment]
Thanks for the useful addition to the issue here, @abspoel.  That approach would be the recommended way to address this issue; it is much more flexible than lastrowid, as it would support multiple inserts or composite key returns values.
