### ISSUE TITLE
Continuous integration build broken

### ISSUE THREAD

**Issue by mfenniak** [mfenniak/pg8000#81]
Hey @tlocke,

Looks like one of your commits recently broke the continuous integration build of pg8000: https://circleci.com/gh/mfenniak/pg8000/78  Any chance you might be able to look into that?

**Comment by tlocke** [comment]
Should be fixed now. I made Postgres 9.4 the main one (instead of 9.3), but forgot to change it for CircleCI. D'oh!

**Comment by mfenniak** [comment]
Thanks!  👍
