### ISSUE TITLE
tzset() on windows

### ISSUE THREAD

**Issue by realazthat** [mfenniak/pg8000#83]
`tzset()` is documented as being unix-only, and is not available on windows. I have had to comment out the line to get the tests to run, and as a result the two related tests fail.

`test_dbapi.py`:

        if not IS_JYTHON:
            os.environ['TZ'] = "UTC"
            time.tzset()

**Comment by tlocke** [comment]
Hi @realazthat, I've pushed a fix to my repo https://github.com/tlocke/pg8000/commit/f44e04e19d478739a07c057d660105f271e86da6 that tests directly for the presence of time.tzset() and so should should skip the tests that can't handle it. Let me know if it works okay on Windows and I'll push it to the main repo.

I realize that it's not ideal to skip tests at all, but I couldn't think of a way of avoiding tzset().

Cheers,

Tony.

**Comment by realazthat** [comment]
It passes.

**Comment by tlocke** [comment]
Cool, I've pushed that to the main repo.
