### ISSUE TITLE
Hi, would like to see something like psycopg2's mogrify()

### ISSUE THREAD

**Issue by realazthat** [mfenniak/pg8000#85]
psycopg2's `Cursor.mogrify()` method returns a formatted string representing the query. This is useful for debugging purposes. Would be nice if we could get this feature here.

**Comment by tlocke** [comment]
Hi, we've got the function pg8000.core.convert_paramstyle(style, query). It returns the query string that's sent to the server. Is that the sort of thing you were looking for?

**Comment by realazthat** [comment]
@tlocke psycopg2's mogrify doesn't use prepared statements, so it is able to output a final SQL with no formatting params left. It seems mostly compatible with the pyformat style, except that it doesn't replace the params with `$1, $2 ...` but rather directly converts it into a non-parameterized pg sql statement.

Since I've posted this comment, I've implemented a `mogrify()` for (aio)pg8000 on my private copy. I used the [node-pg-format](https://github.com/datalanche/node-pg-format/blob/master/lib/index.js) project as a base, which in turn reimplements PG's [format()](http://www.postgresql.org/docs/9.3/static/functions-string.html#FUNCTIONS-STRING-FORMAT) function. I've written some unit tests, that compare it with psycopg2.

I've also implemented simple-query protocol optionally to be used with `execute()`, which actually is a lot of work, since I have to provide non-binary row-data interpretation (on the way back from the server). I've been running it through the unit tests and slowly getting it into shape, and when I am done, it can be contributed to pg8000 if you guys are interested.

**Comment by simplesteph** [comment]
@realazthat can you do a PR? interested in using such function

**Comment by hayd** [comment]
@realazthat it would be nice to see your mogrify function!

**Comment by realazthat** [comment]
@hayd https://github.com/realazthat/aiopg8000/blob/master/aiopg8000/mogrify.py feel free to steal it.
