### ISSUE TITLE
Support for accessing PostgreSQL through PgBouncer

### ISSUE THREAD

**Issue by nt4cats** [mfenniak/pg8000#89]
In my production environment we access Postgresql through PgBouncer in "statement" pooling mode.

For your reference a good summary of pooling modes is available here [End Point's blog](http://blog.endpoint.com/2015/05/connected-to-pgbouncer-or-postgres.html).

When I try to use pg8000 I get errors saying that my prepared statements don't exist.  When I tried to use PyGreSQL in DB-API 2.0 mode I had issues with "long transactions" (explained in the blog post above).

I was able to use PyGreSQL in "classic" mode, this appears to use neither prepared statements nor transactions by default.

I could, possibly, use an older version of pg8000 in its pre-prepared-statement days.  What are the chances of supporting direct/simple queries that do not require prepared statements?

**Comment by realazthat** [comment]
I don't know anything about statement pooling mode, but I have implemented optional simple-query execution (non prepared) in my asyncio fork. The major work isn't changing the mode, but rather the format of the returned data changes from binary format (with prepared statements) to textual format, which means a lot of the data-handling functionality had to be rewritten. I am actually in the midst of committing and pushing this. However, my fork is for the asyncio paradigm, and I would definitely be wary of relying on it for production environments. I do want to backport it to pg8000 as well eventually though; not sure if it would be accepted into the main repo.

**Comment by tlocke** [comment]
@nt4cats I see the problem. On the one hand I'm loathe to add to the complexity of pg800, but on the other I can see that simple query mode would have its uses.
