### ISSUE TITLE
DEFAULT datatype.

### ISSUE THREAD

**Issue by luckydonald** [mfenniak/pg8000#94]
Consider a database with a `NOT NULL` column having a `DEFAULT` value specified.

``` sql
CREATE TABLE test (
    foo VARCHAR(20) NOT NULL DEFAULT 'I am a default value'
);
```

How can I insert a default value

``` sql
INSERT INTO test VALUES (
    DEFAULT
);
```

but using the `%s` syntax

hat is my use-case:

``` python
if condition:
    new_value = "hey, some text"
else:
    new_value = DEFAULT
cur.execute("INSERT INTO test VALUES ( %s )", (new_value,) )
```

I can't use `None`, as it tries to insert `NULL`.
What I am looking for is another [Type Class](http://pythonhosted.org/pg8000/dbapi.html#type-classes) in python, [mapping to](http://pythonhosted.org/pg8000/types.html) PostgreSQL's `DEFAULT`.
Something like

``` python
new_value = pg8000.Default
```

**Comment by mfenniak** [comment]
That's an interesting use-case, and one that hasn't come up here before.  I don't believe I've even seen that supported by other Python / Postgres drivers, either.  Definitely not something supported today, sorry.  As a suggested workaround, you could use multiple queries, dynamically build up your query, or use a library like SQLAlchemy that provides a great low-level SQL interface for query construction.

Your suggested API makes sense, but I'm not confident that implementing it would be straight-forward.  pg8000 sends data queries to the server in a parameterized format -- we don't build up the SQL statement, we just format it the way Postgres expects and provide the type and data of each parameter.  We'd need to dig through the Postgres types and see if there is a type that would identify a bound parameter as the equivalent of the DEFAULT keyword.  If so, this should be straight-forward.

If there a way to identify a bound parameter as a 'DEFAULT' keyword... there are some hacks that are possible, or some structural changes that might make a composed SQL query an alternative to our parameterized query, but, odds are that the amount of work involved in those changes would be too high to justify.

**Comment by realazthat** [comment]
I've got a client-side "mogrify()" implemented in my aiopg8000 fork in https://github.com/realazthat/aiopg8000/blob/master/aiopg8000/mogrify.py, can be of interest to OP. It can possibly be modified to check for special values. It wouldn't work too well with the pg8000's query caching though.

**Comment by luckydonald** [comment]
I came up with the following code:
```python
# a default type to use
class Default(object):
	pass
DEFAULT = Default()

def insert(conn, table_name **kwargs):
	assert isinstance(conn, pg8000.Connection)
	curs=conn.cursor()
	assert isinstance(curs, pg8000.Cursor)

	field_names = []
	field_inserts = []
	field_values = []
	
	# for every item in the kwargs dict, append the key as column name,
	# and append either the placeholder "%s" or DEFAULT
	for key, value in kwargs.items():
		field_names.append(key)
		if not isinstance(value, Default):
			field_inserts.append("%s")
			field_values.append(value)
		else:
			field_inserts.append("DEFAULT")
		# end if
	# end for

	# generate a sql query
	sql = "INSERT INTO {table_name} ({fields}) VALUES ({inserts})".format(
		table_name=table_name,
		fields = ", ".join(field_names),
		inserts = ", ".join(field_inserts)
	)
	# execute the sql query
	curs.execute(sql, tuple(field_values))
	# commit changes
	conn.commit()
```

**Comment by luckydonald** [comment]
I came up with the following function:
```python
insert(connection, "table_name", column_name_1="bla", foo=DEFAULT, bar=1338)
```
Defined as following:
```python
# a default type to use
class Default(object):
	pass
DEFAULT = Default()

def insert(conn, table_name **kwargs):
	assert isinstance(conn, pg8000.Connection)
	curs=conn.cursor()
	assert isinstance(curs, pg8000.Cursor)

	field_names = []
	field_inserts = []
	field_values = []
	
	# for every item in the kwargs dict, append the key as column name,
	# and append either the placeholder "%s" or DEFAULT
	for key, value in kwargs.items():
		field_names.append(key)
		if not isinstance(value, Default):
			field_inserts.append("%s")
			field_values.append(value)
		else:
			field_inserts.append("DEFAULT")
		# end if
	# end for

	# generate a sql query
	sql = "INSERT INTO {table_name} ({fields}) VALUES ({inserts})".format(
		table_name=table_name,
		fields = ", ".join(field_names),
		inserts = ", ".join(field_inserts)
	)
	# execute the sql query
	curs.execute(sql, tuple(field_values))
	# commit changes
	conn.commit()
```

## Detailed Usage example
Consider the following Table:

```sql
CREATE TABLE test (
	foo VARCHAR(20) DEFAULT 'colorful ponies',
	bar INTEGER DEFAULT 4458
);
```
###### Table **test**

|foo|bar|
| --- | --- |
|*DEFAULT 'colorful ponies'"* | *DEFAULT 4458*     |

Insert something:
```python
insert(connection, "test", foo="yay!")
insert(connection, "test", foo=DEFAULT, bar=123)
insert(connection, "test", foo=None)
```
###### Table **test**

|foo|bar|
| --- | --- |
| 'yay' | *4458* |
| *'colorful ponies'* | 123 |
| NULL  | *4458* |
