### ISSUE TITLE
Connection.notifies not populated

### ISSUE THREAD

**Issue by MitaineDomise** [mfenniak/pg8000#95]
Hello, I am trying to use the NOTIFY / LISTEN mechanism but can't seem to get any results in the connection.notifies attribute.

Looking into the pg8000 source, I haven't found any calls to handle_NOTIFICATION_RESPONSE . So maybe this feature was dropped at some point ?

Sorry if I'm missing something obvious, I am very much a beginner !

**Comment by dosmanak** [comment]
Hi. I run into the same problem. I'd like to log the output of a VACUUM command, but I can't get it.

**Comment by dosmanak** [comment]
Hm. So I looked into the source and found I had to add a handler like this:
```
def notifyme(obj):
        prefixes = {
                'M' : 'INFO:\t',
                'D' : 'DETAIL:\t',
        }
        for key in obj.keys():
                if key in prefixes.keys():
                        print prefixes[key]+obj[key]
```

And register handler right after the connect function
`c.NoticeReceived += notifyme`

There could be some documentation on that.
Reffer to:
 - https://github.com/mfenniak/pg8000/blob/master/pg8000/core.py#L1092
 - https://github.com/mfenniak/pg8000/blob/master/pg8000/core.py#L1322

**Comment by tlocke** [comment]
I've simplified how notifications works, and added some documentation. See https://github.com/mfenniak/pg8000/commit/7af4ff5f6eca5535a546102ea6c0e7ff3f646af6
