### ISSUE TITLE
RPM Packaging

### ISSUE THREAD

**Issue by williamjmorenor** [mfenniak/pg8000#96]
Hi I just want to say than I have opened a fedora-review for python-pg8000

https://bugzilla.redhat.com/show_bug.cgi?id=1304522

I wil report here any issue from the review.

**Comment by williamjmorenor** [comment]
I need to ask something, there is any postgresql dependency for this package or can work stand alone without postgresql running in the same host/container.

**Comment by tlocke** [comment]
To answer your question (belatedly!) there's no dependency on postgresql being installed on the same machine. It can connect to a postgresql instance on another machine.

I think the issues you've raised have been dealt with in the 1.10.4 release. If not, please feel free to re-open this issue.
