### ISSUE TITLE
Python 3.2 no longer compatible with CircleCI tests

### ISSUE THREAD

**Issue by tlocke** [mfenniak/pg8000#98]
I found that the master branch now fails on CircleCI:

https://circleci.com/gh/tlocke/pg8000/6

Looking into it, it seems that virtualenv no longer supports Python 3.2.

https://virtualenv.pypa.io/en/latest/changes.html#id7

Would anyone have any objections to dropping support for Python 3.2 in pg8000?

**Comment by mfenniak** [comment]
Makes sense to me.  Python 3.2 is almost five years old, which seems like a reasonable maximum time frame for supporting a release.

**Comment by tlocke** [comment]
I've done some adding and removing of version support for Python and Postgres:

> Removed support for Python 2.5, 2.6 and 3.2, and added support for Python 3.5. Added support for PostgreSQL 9.5.

The commit is at https://github.com/tlocke/pg8000/commit/dc973952f0afcfdc51c1cb4a2650ccc510ca2121

After some trouble with Java SSL certificates I got the CircleCI tests to work:

https://circleci.com/gh/tlocke/pg8000/14

Let me know if there are any objections to this dropping / adding of versions. Otherwise I'll go ahead and push it to the main repo. Thanks!

**Comment by mfenniak** [comment]
Sounds fine to me.  :+1:
