### ISSUE TITLE
Having six library as dependency

### ISSUE THREAD

**Issue by amaramrahul** [mfenniak/pg8000#99]
Hi,
I was trying to package pg8000 for Debian GNU/Linux. One of the concerns was that pg8000 distributes six.py when there is actually another debian package (named python-six) providing six library. Does pg8000 work with six 1.10.0? Is there any reason why six.py is bundled with pg800 rather than having six as a dependency?

Thanks,
Rahul.

**Comment by williamjmorenor** [comment]
I have to check this for #96 thanks for the advice.

**Comment by mfenniak** [comment]
I think 'six' is packaged with pg8000 because it is implicitly supported by the six project (eg. https://pypi.python.org/pypi/six -> 'It is contained in only one Python file, so it can be easily copied into your project.'), and it is common in other projects (eg. https://github.com/django/django/blob/master/django/utils/six.py).

Is there any downside with the embedded approach?  It's "embedded", but it's not like it is exposed to consumers or conflicting with a system-installed six.

**Comment by williamjmorenor** [comment]
Bundled six versión in pg8000 is 1.4.1 and python six available in Fedora and Debian is 1.10.0

See:

https://packages.debian.org/sid/python-six
https://apps.fedoraproject.org/packages/python-six

Fedora packaging guidelines have some rules for bundled libs, allways is preferred use the system lib.:
https://fedoraproject.org/wiki/Bundled_Software_policy

Debian have a more restritive rule for that:
https://wiki.debian.org/UpstreamGuide#Python

I am trying to unbundle the six library in PR #100  but I think this will need more work, looks like suport the six version available in Debian and Fedora will supose drop the suport of python 2.5.

**Comment by williamjmorenor** [comment]
I have some advance here:

https://github.com/williamjmorenor/pg8000/commit/2ec7e728b9ec58566e0ea530eb3346c5feb995ae

The tests pased fine here:
https://circleci.com/gh/williamjmorenor/pg8000/2

**Comment by amaramrahul** [comment]
@mfenniak : One of the main reasons for not preferring embedded libraries is that it puts an additional dependency on tracking them separately. For ex. there might have been some security fixes in python six 1.10.0. How do we ensure that these are backported to the python pg8000 package? Therefore, especially, for distributions such as Debian, it is strongly discouraged to use embedded libraries unless there is a really strong reason to do so.

I have also seen that you have made some modifications to the embedded six library to add compatibility to python version < 2.6. As the minimum version in Debian is anyway 2.6, I have taken the liberty to remove the embedded six library as well as the compatibility changes for python version < 2.6. Attached is the patch that I have used for pg8000 1.10.2. Would be great if you can review and let me know if you see any concerns.

[remove-six-embedded-library.txt](https://github.com/mfenniak/pg8000/files/122625/remove-six-embedded-library.txt)

**Comment by tlocke** [comment]
With the release of 1.10.4, the six library is now unbundled, so you should be able to use the latest release unmodified.
